wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.18
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.8.10
    start_time: 1654999344
    t:
      1:
      - 55
      3:
      - 13
      4: 3.8.10
      5: 0.12.18
      8:
      - 5
